apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "walt-verifier.fullname" . }}-config
  labels: {{- include "walt-verifier.labels" . | nindent 4 }}
data:
{{- range $path, $_ := .Files.Glob "config/*.conf" }}
  {{ base $path }}: |-
{{ tpl ($.Files.Get $path) $ | indent 4 }}
{{- end }}
