{{- if .Values.verifier.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "walt-verifier.serviceAccountName" . }}
  labels: {{- include "walt-verifier.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.verifier.serviceAccount.automountServiceAccountToken }}
{{- end }}
