{{- if .Values.wallet.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "walt-wallet.serviceAccountName" . }}
  labels: {{- include "walt-wallet.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.wallet.serviceAccount.automountServiceAccountToken }}
{{- end }}
