{{- if .Values.issuer.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "walt-issuer.serviceAccountName" . }}
  labels: {{- include "walt-issuer.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.issuer.serviceAccount.automountServiceAccountToken }}
{{- end }}
