apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "verifiably-go.fullname" . }}-config
  labels: {{- include "verifiably-go.labels" . | nindent 4 }}
data:
  backends.json: |-
    {{- toJson .Values.backends | nindent 4 }}
  auth-providers.json: |-
    {{- toJson .Values.authProviders | nindent 4 }}
