{{- if .Values.app.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "verifiably-go.serviceAccountName" . }}
  labels: {{- include "verifiably-go.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.app.serviceAccount.automountServiceAccountToken }}
{{- end }}
