package config

func Default() *Config {
	return &Config{
		Brand: Brand{
			Name:       "vc.infra",
			NameAccent: ".",
		},
		Theme: Theme{
			Light: ThemeColors{
				BG:             "#FAFAF8",
				BGSurface:      "#FFFFFF",
				BGSurfaceAlt:   "#F3F3F0",
				BGOverlay:      "rgba(250, 250, 248, 0.92)",
				Text:           "#1A1A18",
				TextSecondary:  "#6B6B66",
				TextTertiary:   "#9C9C96",
				Border:         "#E4E4E0",
				BorderStrong:   "#CCCCC6",
				Accent:         "#2D5A3D",
				AccentHover:    "#1E3D29",
				AccentSurface:  "#E8F0EB",
				AccentText:     "#FFFFFF",
				TagBG:          "#EEEEE9",
				TagText:        "#4A4A46",
				Success:        "#2D5A3D",
				Warning:        "#8B6914",
				WarningSurface: "#FEF6E0",
				Error:          "#8B2C2C",
				ErrorSurface:   "#FDECEC",
				Info:           "#2D4A5A",
				InfoSurface:    "#E8EFF3",
				ShadowSm:      "0 1px 2px rgba(0,0,0,0.04)",
				ShadowMd:      "0 4px 12px rgba(0,0,0,0.06)",
				ShadowLg:      "0 8px 30px rgba(0,0,0,0.08)",
			},
			Dark: ThemeColors{
				BG:             "#111110",
				BGSurface:      "#1A1A18",
				BGSurfaceAlt:   "#222220",
				BGOverlay:      "rgba(17, 17, 16, 0.92)",
				Text:           "#EAEAE6",
				TextSecondary:  "#9C9C96",
				TextTertiary:   "#6B6B66",
				Border:         "#2E2E2C",
				BorderStrong:   "#444440",
				Accent:         "#5BA97A",
				AccentHover:    "#7BC49A",
				AccentSurface:  "#1A2E22",
				AccentText:     "#111110",
				TagBG:          "#2A2A28",
				TagText:        "#B0B0AA",
				Success:        "#5BA97A",
				Warning:        "#C4962A",
				WarningSurface: "#2A2414",
				Error:          "#C45050",
				ErrorSurface:   "#2A1A1A",
				Info:           "#5A8AA0",
				InfoSurface:    "#1A2228",
				ShadowSm:      "0 1px 2px rgba(0,0,0,0.2)",
				ShadowMd:      "0 4px 12px rgba(0,0,0,0.3)",
				ShadowLg:      "0 8px 30px rgba(0,0,0,0.4)",
			},
		},
		Typography: Typography{
			FontDisplay: "'Josefin Sans', sans-serif",
			FontBody:    "'Geist', -apple-system, 'Segoe UI', system-ui, sans-serif",
			FontMono:    "'Geist Mono', 'SF Mono', 'Consolas', monospace",
			FontURLs: []string{
				"https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@300;400;500;600;700&display=swap",
			},
		},
		Features: Features{
			Workspaces: Workspaces{
				Issuer:   true,
				Holder:   true,
				Verifier: true,
				Trust:    true,
				Admin:    true,
			},
			ExplorationMode: true,
			Chatbot:         true,
		},
		Mode:   "exploration",
		Locale: "en",
	}
}
